import type { DemoState } from "./types";

/** Fictional balances and activity for the public showcase. */
export const DEMO_SEED: DemoState = {
  version: 1,
  locale: "en",
  displayCurrency: "HUF",
  ratesToHuf: { HUF: "1", EUR: "398", USD: "365" },
  institutions: [
    { id: "institution-demo", name: "Demo Broker" },
    { id: "institution-sample", name: "Sample Bank" },
  ],
  accounts: [
    { id: "account-bet", name: "Budapest investments", institutionId: "institution-demo" },
    { id: "account-global", name: "Global markets", institutionId: "institution-demo" },
    { id: "account-bank", name: "Long-term savings", institutionId: "institution-sample" },
  ],
  assets: [
    { id: "asset-otp", name: "OTP Bank Nyrt.", ticker: "OTP", kind: "stock", currency: "HUF", marketPrice: "32500" },
    { id: "asset-mol", name: "MOL Nyrt.", ticker: "MOL", kind: "stock", currency: "HUF", marketPrice: "2970" },
    { id: "asset-richter", name: "Richter Gedeon Nyrt.", ticker: "RICHTER", kind: "stock", currency: "HUF", marketPrice: "10200" },
    { id: "asset-apple", name: "Apple Inc.", ticker: "AAPL", kind: "stock", currency: "USD", marketPrice: "226.5" },
    { id: "asset-microsoft", name: "Microsoft Corp.", ticker: "MSFT", kind: "stock", currency: "USD", marketPrice: "510.3" },
    { id: "asset-world-etf", name: "Vanguard FTSE All-World ETF", ticker: "VWRL", kind: "etf", currency: "EUR", marketPrice: "142.7" },
    { id: "asset-fixmap", name: "FixMÁP", ticker: "FIXMAP", kind: "bond", currency: "HUF", marketPrice: "101.45" },
    { id: "asset-mapplus", name: "MÁP Plusz", ticker: "MAPPLUS", kind: "bond", currency: "HUF", marketPrice: "103.21" },
    { id: "asset-art", name: "Art collection", ticker: "ART", kind: "other", currency: "HUF", marketPrice: "950000" },
  ],
  cash: [
    { accountId: "account-bet", currency: "HUF", amount: "750000" },
    { accountId: "account-bet", currency: "EUR", amount: "100" },
    { accountId: "account-bet", currency: "USD", amount: "50" },
    { accountId: "account-global", currency: "HUF", amount: "0" },
    { accountId: "account-global", currency: "EUR", amount: "300" },
    { accountId: "account-global", currency: "USD", amount: "400" },
    { accountId: "account-bank", currency: "HUF", amount: "240000" },
    { accountId: "account-bank", currency: "EUR", amount: "0" },
    { accountId: "account-bank", currency: "USD", amount: "0" },
  ],
  positions: [
    { accountId: "account-bet", assetId: "asset-otp", units: "30" },
    { accountId: "account-bet", assetId: "asset-mol", units: "160" },
    { accountId: "account-bet", assetId: "asset-richter", units: "24" },
    { accountId: "account-global", assetId: "asset-apple", units: "14" },
    { accountId: "account-global", assetId: "asset-microsoft", units: "5" },
    { accountId: "account-global", assetId: "asset-world-etf", units: "32" },
    { accountId: "account-bank", assetId: "asset-fixmap", units: "40000" },
    { accountId: "account-bank", assetId: "asset-mapplus", units: "25000" },
    { accountId: "account-bank", assetId: "asset-art", units: "1" },
  ],
  transactions: [
    { id: "sample-001", date: "2025-10-03", action: "deposit", accountId: "account-bet", assetId: null, units: null, price: null, currency: "HUF" },
    { id: "sample-002", date: "2025-10-14", action: "buy", accountId: "account-bet", assetId: "asset-otp", units: "20", price: "28600", currency: "HUF" },
    { id: "sample-003", date: "2025-11-12", action: "buy", accountId: "account-global", assetId: "asset-world-etf", units: "12", price: "133.4", currency: "EUR" },
    { id: "sample-004", date: "2025-12-04", action: "dividend", accountId: "account-global", assetId: "asset-apple", units: null, price: "18.2", currency: "USD" },
    { id: "sample-005", date: "2026-01-08", action: "interest", accountId: "account-bank", assetId: "asset-fixmap", units: null, price: "14600", currency: "HUF" },
    { id: "sample-006", date: "2026-02-18", action: "buy", accountId: "account-bet", assetId: "asset-mol", units: "60", price: "2760", currency: "HUF" },
    { id: "sample-007", date: "2026-03-23", action: "sell", accountId: "account-global", assetId: "asset-world-etf", units: "3", price: "139.8", currency: "EUR" },
    { id: "sample-008", date: "2026-04-07", action: "dividend", accountId: "account-bet", assetId: "asset-mol", units: null, price: "8400", currency: "HUF" },
    { id: "sample-009", date: "2026-05-19", action: "buy", accountId: "account-global", assetId: "asset-microsoft", units: "2", price: "486.2", currency: "USD" },
    { id: "sample-010", date: "2026-06-11", action: "interest", accountId: "account-bank", assetId: "asset-mapplus", units: null, price: "19200", currency: "HUF" },
    { id: "sample-011", date: "2026-07-16", action: "sell", accountId: "account-bet", assetId: "asset-mol", units: "12", price: "3030", currency: "HUF" },
    { id: "sample-012", date: "2026-09-22", action: "buy", accountId: "account-bet", assetId: "asset-richter", units: "4", price: "9850", currency: "HUF" },
  ],
  history: [
    { date: "2025-10-31", totalHuf: "10320000" },
    { date: "2025-11-30", totalHuf: "10510000" },
    { date: "2025-12-31", totalHuf: "10280000" },
    { date: "2026-01-31", totalHuf: "10640000" },
    { date: "2026-02-28", totalHuf: "10910000" },
    { date: "2026-03-31", totalHuf: "10780000" },
    { date: "2026-04-30", totalHuf: "11260000" },
    { date: "2026-05-31", totalHuf: "11750000" },
    { date: "2026-06-30", totalHuf: "12180000" },
    { date: "2026-07-31", totalHuf: "12810000" },
    { date: "2026-08-31", totalHuf: "13690000" },
    { date: "2026-09-30", totalHuf: "14400000" },
  ],
};
